### ISSUE TITLE
How do I merge multiple .rdb files into one?

### ISSUE THREAD

**Issue by aligajani** [sripathikrishnan/redis-rdb-tools#84]

**Comment by oranagra** [comment]
you can try this:
* start an empty redis server
* use the redis-rdb-tools [protocol emitter](https://github.com/sripathikrishnan/redis-rdb-tools/blob/master/README.md#emitting-redis-protocol) in order to convert the rdb to commands and send the commands to the server.
* repeat the above for each rdb you want to merge
* issue a SAVE command on the redis to save a new file.
